- name: Add SSHD config
  copy:
    dest: /etc/ssh/sshd_config
    src: sshd_config
    owner: root
    group: root
    mode: 0600

- name: Remove SSH from public zone
  firewalld:
    zone: public
    service: ssh
    state: disabled
    immediate: yes
    permanent: yes

- name: Add SSH to internal zone
  firewalld:
    zone: internal
    service: ssh
    state: enabled
    immediate: yes
    permanent: yes

- name: Reload SSH
  service:
    name: sshd
    state: reloaded

- name: Reload firewalld
  service:
    name: firewalld
    state: reloaded
